### ISSUE TITLE
Multiple search tokens on relations not supported

### ISSUE THREAD

**Issue by alex-hoppe** [Servoy/svySearch#13]
Suppose I have a table relation 'contact_to_contact_car.car_color' added as a search provider.
Searching for 'blue' will bring up all contacts who have blue cars.
Searching for 'blue red' will load no records, even if there are contacts who have blue cars and red cars.

**Comment by seanthomasdevlin** [comment]
Hi Alex,

Multiple search tokens are supported across relations, however, this may be an artifact searching for multiple tokens on the same data provider.

This can be reproduced in the sample solution, i.e. search "coffee chai", yields the SQL:
`where upper(products.productname) like ? and upper(products.productname) like ?`
`['coffee','chai']`

But I'm not sure there is much we can do.

This is because the nature of the search requires that ALL (logical AND) search tokens must match ANY (logical OR) of the search providers.

essentially:
`(providerA=token1 OR providerB=token1) AND (providerA=token2 OR providerB=token2)`

And when providerB doesn't match (or exist), then you get:
`providerA=token1  AND providerA=token2`

We cannot invert this arrangement because it would break the contract of ensuring that every token is matched. 

For example:
`(providerA=token1 OR providerA=token2) AND (...)`

we cannot know which token matched and cannot guarantee that ALL have matched

**Comment by seanthomasdevlin** [comment]
With regards specifically to related providers, this is a problem, because the user really expects to get a record that matches both tokens in a related table. Perhaps this can be solved with a SQL HAVING clause if we detect multiple tokens and a related provider. Although, this will be really complicated to implement

We could also experiment with a kind of Mode to the SimpleSearch class, where you adjust how strictly tokens are matched. Disabling strict mode, would be, in effect, all ORs. (Although this may be disorienting to a user, breaks the contract, not how an internet search engine works)

**Comment by seanthomasdevlin** [comment]
Closed due to inactivity
