### ISSUE TITLE
Exclude operator

### ISSUE THREAD

**Issue by alex-hoppe** [Servoy/svySearch#14]
Our users are having some trouble with the exclude operator and I was wondering what to tell them as far as how to properly perform the search.

Searching for _**+rat**_ will perform an exact search, and only brings up records with rat, not mole rat or laboratory. However, typing **_-rat_** will not only exclude rats, but mole rats and any laboratories as well. Typing _**laboratory -rat**_ will not load any records at all.
As another example, searching **_-pig_** will exclude all records with pig, guinea pig, or epigenetics.

I think what is happening is that the plus operator indicates an exact match, but the minus operator searches for in-string matches. So it seems to be related to this issue: https://github.com/Servoy/svySearch/issues/10

**Comment by seanthomasdevlin** [comment]
Hi Alex,

Thanks for your interest in the search module.
The "contains" matching on the exclude operator is expected behavior.

We could look into changing it to be more of an exact match, but that could break other implementations which rely on the contains.

Perhaps we can support quoting the excluded string to indicate an exact match.
Something like **-"rat"**

I will look into it....
