### ISSUE TITLE
Unable to use search with Numbers

### ISSUE THREAD

**Issue by Dracohydrus** [Servoy/svySearch#17]
When using a number as a search provider, the results are not filtered at all.

**Comment by seanthomasdevlin** [comment]
numeric columns are not supported for **implied search** because of the difficulty in comparing them to supported expressions, i.e. (>50)

But numeric columns can be searched using **explicit** search terms.
i.e.
`searchText="orderid:10248"`

**Comment by seanthomasdevlin** [comment]
This would be tricky to support it implied search because we really treat it like text when the alias is not specified. it wants to query something with string and wildcards. We change that when we know the column that was requested with the explicit syntax alias:value. I'll look into how much work it is. (not trivial)...

As a work-around, you could pre-parse this yourself. Something like:
`searchText = myPK + ':' + searchText`
Once you know it was requested, perhaps using parseint() with a try/catch

**Comment by Dracohydrus** [comment]
I understand this is not an easy thing to add. I was more so curious about
treating a number field almost as a string. Currently you are talking about
doing number comparisons but what if I wanted to find all numbers starting
with '46'. This would be done easier by treating the 46 as a string and
using a wild card at the end of it. Maybe it would be easier to do it this
way, have an option to view search provider values as a string instead of
whatever type they are?
