### ISSUE TITLE
searching for something like "5:1"

### ISSUE THREAD

**Issue by pdeg001** [Servoy/svySearch#5]
In our solution we have a column that contains values like 5:1 or 7:2, when we try to search for 5: 1 and we type the search string like "5:1" then the following message show in the log

**WARN Search alias not found: 5 . Search term will be ignored**

Is there a workaround for this issue?

**Comment by seanthomasdevlin** [comment]
This is a bug. "5.1" is a valid search term and the quotes should escape the colon.
There is also [another issue](https://github.com/Servoy/svySearch/issues/4) that quoted values on an alias search are not working. i.e. field:"my value"
And It's a bit tricky to support both because of the order of processing...

**Comment by seanthomasdevlin** [comment]
Fixed

Do note that only stand-alone terms are currently quote-able. Terms
with a field alias are not supported at this time (see [issue #4](https://github.com/Servoy/svySearch/issues/4))
