### ISSUE TITLE
Searching through different DB's

### ISSUE THREAD

**Issue by pdeg001** [Servoy/svySearch#6]
Hi,

I can show data form different databases via an relation within the same database container, like below,
![diffdbs](https://cloud.githubusercontent.com/assets/4630171/20884875/12f852b6-baee-11e6-99f8-448f64d7dbb4.png)

the relation looks like this **projects_to_refdb_projects**, and it shows one or more records

![relationresult](https://cloud.githubusercontent.com/assets/4630171/20884962/87f36aa6-baee-11e6-9c46-82f8a7be313d.png)

But when I add the relation and field as an searchprovider I get an error,
`.addSearchProvider('projects_to_refdb_projects.projectmanager').setAlias('pm');`

`QBSelect(SELECT Mneme:dbo:projects<db:/mneme/projects>#projects564.1073742721=project_id<4,0,0> FROM Mneme:dbo:projects<db:/mneme/projects>#projects564 <anonymous> ((UPPER[RefDb:dbo:PROJECTS<db:/refdb/projects>#PROJECTS565.1073742790=ProjectManager<-9,50,0>] null)LIKE([<anonymous>=%PRUI%])) LEFT OUTER JOIN projects_to_refdb_projects FROM Mneme:dbo:projects<db:/mneme/projects>#projects564 TO RefDb:dbo:PROJECTS<db:/refdb/projects>#PROJECTS565 ON ((RefDb:dbo:PROJECTS<db:/refdb/projects>#PROJECTS565.1073742787=Project_no<12,10,0>)=([Mneme:dbo:projects<db:/mneme/projects>#projects564.1073742748=project_number_string<-9,50,0>])))
java.lang.IllegalStateException: Could not resolve column PROJECTS<db:/refdb/projects>#PROJECTS571.1073742790=?
Wrapped com.servoy.j2db.persistence.RepositoryException: java.lang.IllegalStateException: Could not resolve column PROJECTS<db:/refdb/projects>#PROJECTS571.1073742790=? (C:\Users\GROOT00P\servoy_workspace_22012016\svySearch\svySearch.js#635)`

I'm I doing something wrong?

Regards,
Peter

**Comment by seanthomasdevlin** [comment]
Hi Peter,

All relations used must be within the same database as the table being searched.
SvySearch uses the QBSelect API from Servoy which cannot support cross-DB relations in a direct query.
The same is true of Servoy find mode. This is because any query generated will use SQL JOIN (x-db join not supported in all DB vendors)

(The reason you are not limited in showing x-db relations on a form is that it is generating individual queries with SQL WHERE pk = fk)

I have committed a change which logs a warning when addSearchProvider is called using x-db relation.
addSearchProvider will return null in this case.
